version: '3.5'
services:
  mongodb:
    image: mongo:6.0-jammy

    container_name: mongodb

    ports:
      - "27017:27017"

    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}

    volumes:
      - mongodb:/data/db

    networks:
      - backend

    restart: 
      always

networks:
  backend:

volumes:
  mongodb:
